---
- name: deploy 000-default-vhost.conf template
  template:
    src: '000-default-vhost.conf.j2'
    dest: "{{ apache_conf_root }}/conf.d/000-default-vhost.conf"
    owner: root
    group: root
    setype: "httpd_config_t"
    mode: 0644
  notify:
    - reload apache
    - enable apache

- name: Make /var/www/html directory if not exists
  file:
    path: /var/www/html
    owner: root
    group: root
    mode: 0755
    state: directory

- name: deploy default index.html
  copy:
    src: 'templates/default-index.html'
    dest: "/var/www/html/index.html"
    owner: root
    group: root
    setype: "httpd_config_t"
    mode: 0644
  notify:
    - reload apache
    - enable apache
