---
# handlers file for apache24-config

- name: enable apache
  service:
    name: "{{ apache_service_name }}"
    enabled: yes

- name: disable apache
  service:
    name: "{{ apache_service_name }}"
    enabled: no

- name: restart apache
  service:
    name: "{{ apache_service_name }}"
    state: restarted

- name: reload apache
  service:
    name: "{{ apache_service_name }}"
    state: reloaded

- name: start apache
  service:
    name: "{{ apache_service_name }}"
    state: started

- name: stop apache
  service:
    name: "{{ apache_service_name }}"
    state: stopped